export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_TEACHER_ACTIVE_COMPONENT = 'SET_TEACHER_ACTIVE_COMPONENT';
export const SET_TEACHER_ACTIVE_CLASS = 'SET_TEACHER_ACTIVE_CLASS';
export const SET_TEACHER_CLASSES = 'SET_TEACHER_CLASSES';
export const SET_CLASS_STUDENT_VALUES = 'SET_CLASS_STUDENT_VALUES';
export const RESET_DEFAULTS_TEACHER = 'RESET_DEFAULTS_TEACHER';
